// Code generated by Wire. DO NOT EDIT.

package bootstrap

import (
	"ptm-indonesia/config"
	"ptm-indonesia/controllers"
	"ptm-indonesia/helper"
	"ptm-indonesia/repository"
	repositoryContract "ptm-indonesia/repository/contract"
	"ptm-indonesia/services"
	servicesContract "ptm-indonesia/services/contract"
	"ptm-indonesia/validation"
)

func InitializeHTTPApplication() (*HTTPApplication, func(), error) {
	appConfig, err := config.NewAppConfig()
	if err != nil {
		return nil, nil, err
	}

	logger, cleanup, err := config.NewLogger(appConfig)
	if err != nil {
		return nil, nil, err
	}

	database, cleanup2, err := config.NewDatabase(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}

	bundle, err := config.NewI18nBundle()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}

	localizer := helper.NewLocalizer(bundle, appConfig)
	responder := helper.NewResponder()
	googleOIDCClient, err := helper.NewGoogleOIDCClient(appConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sessionTokenManager := helper.NewSessionTokenManager(appConfig)
	refreshTokenManager := helper.NewRefreshTokenManager(appConfig)

	requestValidator, err := validation.NewRequestValidator(appConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}

	systemRepository := repository.NewSystemRepository(database)
	var systemRepositoryContract repositoryContract.SystemRepository = systemRepository
	userRepository := repository.NewUserRepository(database)
	var userRepositoryContract repositoryContract.UserRepository = userRepository
	refreshTokenRepository := repository.NewRefreshTokenRepository(database)
	var refreshTokenRepositoryContract repositoryContract.RefreshTokenRepository = refreshTokenRepository
	healthService := services.NewHealthService(appConfig, systemRepositoryContract)
	var healthServiceContract servicesContract.HealthService = healthService
	var googleOIDCClientContract servicesContract.GoogleOIDCClient = googleOIDCClient
	var sessionTokenManagerContract servicesContract.SessionTokenManager = sessionTokenManager
	var refreshTokenManagerContract servicesContract.RefreshTokenManager = refreshTokenManager
	authService := services.NewAuthService(googleOIDCClientContract, sessionTokenManagerContract, refreshTokenManagerContract, userRepositoryContract, refreshTokenRepositoryContract)
	var authServiceContract servicesContract.AuthService = authService
	userService := services.NewUserService(appConfig, userRepositoryContract)
	var userServiceContract servicesContract.UserService = userService
	healthController := controllers.NewHealthController(healthServiceContract, responder, localizer)
	authController := controllers.NewAuthController(appConfig, authServiceContract, responder, localizer)
	userController := controllers.NewUserController(appConfig, authServiceContract, userServiceContract, responder, localizer)
	app := NewFiberApp(appConfig, logger, localizer, requestValidator, healthController, authController, userController)
	httpApplication := NewHTTPApplication(appConfig, app, logger)

	cleanupAll := func() {
		cleanup2()
		cleanup()
	}

	return httpApplication, cleanupAll, nil
}
