root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -buildvcs=false -o ./tmp/api ./cmd/api"
  entrypoint = ["./tmp/api"]
  include_ext = ["go", "json", "sql"]
  exclude_dir = ["tmp", "logs", "bin", ".git"]
  stop_on_error = true

[build.windows]
  cmd = "go build -buildvcs=false -o ./tmp/api.exe ./cmd/api"
  entrypoint = ["tmp\\api.exe"]

[log]
  time = true
